services:
  selfhelp.api:
    image: selfhelp_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_HTTP_PORT_URLS=http://+:5000
